# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XYZ Foods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XYZ Foods

  target 'XYZ FoodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XYZ FoodsUITests' do
    # Pods for testing
  end

pod 'SideMenu'

end
